apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\The_F\Downloads\kompose-windows-amd64 (1).exe convert -f C:\Users\The_F\source\repos\Miro-Services\src\docker-compose.yml -v
    kompose.version: 1.37.0 (fb0539e64)
  labels:
    io.kompose.service: identydb
  name: identydb
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: identydb
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\The_F\Downloads\kompose-windows-amd64 (1).exe convert -f C:\Users\The_F\source\repos\Miro-Services\src\docker-compose.yml -v
        kompose.version: 1.37.0 (fb0539e64)
      labels:
        io.kompose.service: identydb
    spec:
      containers:
        - env:
            - name: SA_PASSWORD
              value: N@tional55
          image: mcr.microsoft.com/mssql/server
          name: identydb
      restartPolicy: Always
